/**
 * @internalapi
 * @category Tezos
 */
/**
 * @internalapi
 * @category Tezos
 */
export type MichelsonPrimitives =
  | MichelsonNoArgInstructionID
  | MichelsonRegularInstructionID
  | MichelsonSimpleComparableTypeID
  | MichelsonTypeID
  | MichelsonDataID

type MichelsonNoArgInstructionID =
  | 'ABS'
  | 'ADD'
  | 'ADDRESS'
  | 'AMOUNT'
  | 'AND'
  | 'APPLY'
  | 'BALANCE'
  | 'BLAKE2B'
  | 'BYTES'
  | 'CAR'
  | 'CDR'
  | 'CHAIN_ID'
  | 'CHECK_SIGNATURE'
  | 'COMPARE'
  | 'CONCAT'
  | 'CONS'
  | 'EDIV'
  | 'EQ'
  | 'EXEC'
  | 'FAILWITH'
  | 'GE'
  | 'GET_AND_UPDATE'
  | 'GT'
  | 'HASH_KEY'
  | 'IMPLICIT_ACCOUNT'
  | 'INT'
  | 'ISNAT'
  | 'JOIN_TICKETS'
  | 'KECCAK'
  | 'LE'
  | 'LEVEL'
  | 'LOG2'
  | 'LSL'
  | 'LSR'
  | 'LT'
  | 'MEM'
  | 'MIN_BLOCK_TIME'
  | 'MUL'
  | 'NAT'
  | 'NEG'
  | 'NEQ'
  | 'NEVER'
  | 'NOT'
  | 'NOW'
  | 'OPEN_CHEST'
  | 'OR'
  | 'PACK'
  | 'PAIRING_CHECK'
  | 'READ_TICKET'
  | 'RENAME'
  | 'SAPLING_VERIFY_UPDATE'
  | 'SELF'
  | 'SELF_ADDRESS'
  | 'SENDER'
  | 'SET_DELEGATE'
  | 'SHA256'
  | 'SHA3'
  | 'SHA512'
  | 'SIZE'
  | 'SLICE'
  | 'SOME'
  | 'SOURCE'
  | 'SPLIT_TICKET'
  | 'SUB'
  | 'SUB_MUTEZ'
  | 'SWAP'
  | 'TICKET'
  | 'TICKET_DEPRECATED'
  | 'TOTAL_VOTING_POWER'
  | 'TRANSFER_TOKENS'
  | 'UNIT'
  | 'VOTING_POWER'
  | 'XOR'

type MichelsonRegularInstructionID =
  | 'CAST'
  | 'CONTRACT'
  | 'CREATE_ACCOUNT'
  | 'CREATE_CONTRACT'
  | 'DIG'
  | 'DIP'
  | 'DROP'
  | 'DUG'
  | 'DUP'
  | 'EMPTY_BIG_MAP'
  | 'EMPTY_MAP'
  | 'EMPTY_SET'
  | 'EMIT'
  | 'GET'
  | 'IF'
  | 'IF_CONS'
  | 'IF_LEFT'
  | 'IF_NONE'
  | 'ITER'
  | 'LAMBDA'
  | 'LAMBDA_REC'
  | 'LEFT'
  | 'LOOP'
  | 'LOOP_LEFT'
  | 'MAP'
  | 'NIL'
  | 'NONE'
  | 'PAIR'
  | 'PUSH'
  | 'RIGHT'
  | 'SAPLING_EMPTY_STATE'
  | 'STEPS_TO_QUOTA'
  | 'UNPACK'
  | 'UNPAIR'
  | 'UPDATE'
  | 'VIEW'

export type MichelsonSimpleComparableTypeID =
  | 'address'
  | 'bool'
  | 'bytes'
  | 'chain_id'
  | 'int'
  | 'key'
  | 'key_hash'
  | 'mutez'
  | 'nat'
  | 'never'
  | 'signature'
  | 'string'
  | 'timestamp'
  | 'tx_rollup_l2_address'
  | 'unit'

export type MichelsonTypeID =
  | MichelsonSimpleComparableTypeID
  | 'big_map'
  | 'bls12_381_fr'
  | 'bls12_381_g1'
  | 'bls12_381_g2'
  | 'chest'
  | 'chest_key'
  | 'contract'
  | 'lambda'
  | 'list'
  | 'map'
  | 'operation'
  | 'option'
  | 'or'
  | 'pair'
  | 'sapling_state'
  | 'sapling_transaction'
  | 'sapling_transaction_deprecated'
  | 'set'
  | 'ticket'

export type MichelsonDataID =
  | 'False'
  | 'Lambda_rec'
  | 'Left'
  | 'None'
  | 'Pair'
  | 'Right'
  | 'Some'
  | 'True'
  | 'Unit'
