/**
 * @publicapi
 * @category Tezos
 */
export enum TezosOperationType {
  ACTIVATE_ACCOUNT = 'activate_account',
  ATTESTATION = 'attestation',
  ATTESTATIONS_AGGREGATE = 'attestations_aggregate',
  ATTESTATION_WITH_DAL = 'attestation_with_dal',
  BALLOT = 'ballot',
  DAL_PUBLISH_COMMITMENT = 'dal_publish_commitment',
  DELEGATION = 'delegation',
  DRAIN_DELEGATE = 'drain_delegate',
  DOUBLE_ATTESTATION_EVIDENCE = 'double_attestation_evidence',
  DOUBLE_BAKING_EVIDENCE = 'double_baking_evidence',
  DOUBLE_ENDORSEMENT_EVIDENCE = 'double_endorsement_evidence',
  DOUBLE_PREATTESTATION_EVIDENCE = 'double_preattestation_evidence',
  DOUBLE_PREENDORSEMENT_EVIDENCE = 'double_preendorsement_evidence',
  ENDORSEMENT = 'endorsement',
  ENDORSEMENT_WITH_DAL = 'endorsement_with_dal',
  EVENT = 'event',
  FAILING_NOOP = 'failing_noop',
  INCREASE_PAID_STORAGE = 'increase_paid_storage',
  ORIGINATION = 'origination',
  PREATTESTATION = 'preattestation',
  PREATTESTATIONS_AGGREGATE = 'preattestations_aggregate',
  PREENDORSEMENT = 'preendorsement',
  PROPOSALS = 'proposals',
  REGISTER_GLOBAL_CONSTANT = 'register_global_constant',
  REVEAL = 'reveal',
  SEED_NONCE_REVELATION = 'seed_nonce_revelation',
  SET_DEPOSITS_LIMIT = 'set_deposits_limit',
  SMART_ROLLUP_ADD_MESSAGES = 'smart_rollup_add_messages',
  SMART_ROLLUP_CEMENT = 'smart_rollup_cement',
  SMART_ROLLUP_EXECUTE_OUTBOX_MESSAGE = 'smart_rollup_execute_outbox_message',
  SMART_ROLLUP_ORIGINATE = 'smart_rollup_originate',
  SMART_ROLLUP_PUBLISH = 'smart_rollup_publish',
  SMART_ROLLUP_RECOVER_BOND = 'smart_rollup_recover_bond',
  SMART_ROLLUP_REFUTE = 'smart_rollup_refute',
  SMART_ROLLUP_TIMEOUT = 'smart_rollup_timeout',
  TICKET_UPDATES = 'ticket_updates',
  TRANSACTION = 'transaction',
  TRANSFER_TICKET = 'transfer_ticket',
  UPDATE_CONSENSUS_KEY = 'update_consensus_key',
  UPDATE_COMPANION_KEY = 'update_companion_key',
  VDF_REVELATION = 'vdf_revelation',
  DOUBLE_CONSENSUS_OPERATION_EVIDENCE = 'double_consensus_operation_evidence',
  DAL_ENTRAPMENT_EVIDENCE = 'dal_entrapment_evidence'
}
