name: Validate Wallet Logos

on:
  pull_request:
    paths:
      - 'assets/logos/**'
      - 'scripts/blockchains/**'

jobs:
  validate-logos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install sharp
        
    - name: Validate Logo Files
      run: node scripts/validate-logos.js
        
    - name: Check Logo Naming Convention
      run: node scripts/check-logo-naming.js